### ISSUE TITLE
Is there a way to know what websocket error it throws?

### ISSUE THREAD

**Issue by yingfangdu** [JsCommunity/jsonrpc-websocket-client#41]
Hi,
When I use the library, I got a couple of different WebSocket connection failures of ERR_CONNECTION_REFUSED, ERR_NETWORK_IO_SUSPENDED or ERR_CONNECTION_TIMED_OUT

Is there a way that I get the detail error thrown from WebSocket instead of simply a ConnectionError  without much information?

Thanks very much.

**Comment by julien-f** [comment]
Hi,

When do you get this error?

Can you show me a small code reproducing the issue?

**Comment by yingfangdu** [comment]
Thanks for reply.
ERR_CONNECTION_REFUSED is easy to repro locally if you let the WebSocket connect to some port that no server is listening too.

ERR_NETWORK_IO_SUSPENDED happens when the machine just goes to sleep mode, you can use a laptop and set the power plan like this.

![image](https://user-images.githubusercontent.com/9310605/55975730-7957c100-5c3f-11e9-8721-213da85d8ea2.png)

ERR_CONNECTION_TIMED_OUT I cannot repro it. I guess maybe the server is very busying and do not reply in a required time frame.

**Comment by julien-f** [comment]
Released as 0.5.0, thank you for your report.
